---
###
#
##

meta:
  product_slug:               pas-windows
  product_name:               (( grab meta.product_slug ))

  glob:                       '*.pivotal'

  windows:                    true

  # When artifactory_stemcell environment feature is enabled
  artifactory_stemcell:
    repository:               "/YOUR_TEAM/windows-stemcells"
    regex:                    "bosh-stemcell-(?<version>.*).tgz"
