---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: bonzofenix/alpine-ci-tools
    tag: edge

params:
  DEBUG:
  BOSH_TARGET:
  BOSH_CLIENT:
  BOSH_CLIENT_SECRET:
  BOSH_CA_CERT:
  DEPLOYMENT_NAME:
  BBR_USERNAME:
  BBR_PASSWORD:

inputs:
  - name: pipeline

outputs:
  - name: output

run:
  path: pipeline/ci/scripts/backup.sh
