---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: bonzofenix/alpine-ci-tools
    tag: v0.0.5

params:
  OM_TARGET:
  OM_CLIENT_ID:
  OM_CLIENT_SECRET:
  OM_USERNAME:
  OM_PASSWORD:
  OM_SKIP_SSL_VALIDATION: false
  OM_REQUEST_TIMEOUT: 3600
  PIVNET_API_TOKEN:

inputs:
  - name: tile
  - name: pipeline

outputs:
  - name: stemcell

run:
  path: pipeline/ci/scripts/get-stemcell.sh

