---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: bonzofenix/ci-tools
    version: v0.1.6

params:
  DEBUG: false
  OM_TARGET:
  OM_CLIENT_ID:
  OM_CLIENT_SECRET:
  OM_USERNAME:
  OM_PASSWORD:
  OM_SKIP_SSL_VALIDATION: false
  OM_REQUEST_TIMEOUT: 3600
  VAULT_ADDR:
  VAULT_TOKEN:
  VAULT_SKIP_VERIFY:
  PRODUCT_NAME:
  YAML2VAULT_PREFIX:
  NETWORK_FILE:
  PROPERTIES_FILE:
  RESOURCES_FILE:
  ERRANDS_FILE:
  STORE_FILE:

inputs:
  - name: pipeline
  - name: config
  - name: metadata

outputs:
  - name: config-mod
# - name: output      # For debugging purposes, uncomment

run:
  path: pipeline/ci/scripts/deploy.sh
