---
name: cf
git_project: https://github.com/bonzofenix/tile-ta-deployment.git

features:
  tile_updates: true
  slack_updates: true
  pin_versions: true

envs:
- name: some_env
  features:
    allow_destroy: true
